#FAT32 is split into 3 main sections:
#	Boot record
#	File allocation table
#	directory and data area


#Extract values from BPB
MOV FAT32.total_sec_32 INTO total_secs

MOV FAT32.sec_p_table_32 INTO fat_size

#(root_entry_cnt * 32) + (bytes_p_sec - 1) / bytes_p_sec = (0) + 511 / 512 round up = 1
#SUB FAT32.bytes_p_sec N_[1] INTO root_dir_secs
#DIV
MOV N_[1] INTO root_dir_secs

#FAT32.reserved_cnt + (FAT32.table_cnt * fat_size) + root_dir_secs
MULT N_[2] fat_size INTO first_data_sec
ADD first_data_sec FAT32.reserved_cnt INTO first_data_sec
ADD first_data_sec root_dir_secs INTO first_data_sec

MOV FAT32.reserved_cnt INTO first_fat_sec

#FAT32.total_sec 




#Reading Directories





###########		Declarations 		############
#Boot Record
#BPB(BIOS PARAM BLOCK)
#OFFSET		SIZE				(IN BYTES)
#0			3 		EB 3C 90
#3			8 		29 3A 63 7E 2D 49 48 43
#11			2		# BYTES PER SECTOR
#13			1		# SECTORS PER CLUSTER
#14			2		# RESERVED SECTORS
#16			1		# OF FAT's (OFTEN 2)
#17			2		# OF DIRECTORY ENTRIES
#19			2		TOTAL SECTORS IN LOGICAL VOLUME
#21			1		MEDIA DISCRIPTOR TYPE
#22			2		# SECTORS PER FAT
#24			2		# SECTORS PER TRACK
#26			2		# HEADS 
#28			4		# HIDDEN SECTORS
#32			4		LARGE AMOUNT OF SECTOR ON MEDIA (SET IF > 65535 SECTORS IN VOLUME)
#36			4		# SECTORS PER FAT
#40			2		FLAGS
#42			2		FAT VERSION NUMBER
#44			4		CLUSTER # OF ROOT DIR
#48			2		SECTOR # OF FSINFO STRUCT
#50			2		SECTOR NUMBER OF BACKUP BOOT SECTOR
#52			12		RESERVED. WHEN VOLUME FORMATTED SHOULD BE 0
#64			1		DRIVE #
#65			1		RESERVED		
#66			1		SIGNATURE(0x28 OR 0x29)
#67			4		VOLUMEID 'SERIAL' NUMBER
#71			11		VOLUME LABEL STRING - PADDED WITH SPACES
#82			8		ALWAYS "FAT32   "
#90			420		BOOT CODE
#510		2		0xAA55 BOOTABLE PARTITION SIG

FAT32.bootjmp			.data	6	0xEB3C90
FAT32.oem_name			.data	16	0x293A637E2D494843
FAT32.bytes_p_sec		.data	4	512 #(one of 512,1024,2048, or 4096)
FAT32.sec_p_clust		.data	2	1 	#(one of 1,2,4,8,16,32,64,128)
FAT32.reserved_sec		.data	4	32
FAT32.table_cnt			.data	2	2
FAT32.root_entry_cnt	.data	4	0
FAT32.total_sec_16		.data	4	0
FAT32.media_type		.data	2	0xF8
FAT32.sec_p_table_16	.data	4	0
FAT32.sec_p_track		.data	4	12	#(Sectors per track for interrupt 0x13)
FAT32.head_cnt			.data	4	2	#(# heads for interupt 0x13)
FAT32.hidden_sec_cnt	.data	8	0	#(0 if not partioned, otherwise only relevent for interrupt 0x13)
FAT32.total_sec_32		.data	8		#(Must be non 0)

FAT32.sec_p_table_32	.data	8		#(FAT32 32-bit count of secs operated by one fat)
FAT32.flags				.data	4		#(0-3 zero-based num of active fat 4-6 reserved 7 1 8-15 reserved)
FAT32.fat_version		.data	4		#(version # of fat32 volume)
FAT32.root_clust		.data	8	2
FAT32.fat_info			.data	4	1
FAT32.backup_bs_sec		.data	4	6
FAT32.reserved_0		.data	24	
FAT32.drive_num			.data	2	0x80
FAT32.reserved_1		.data	2	0
FAT32.boot_sig			.data	2	0x29
FAT32.volume_id			.data	8	#(usually generated by combined current date+time into 32 bits)
FAT32.volume_label		.data	22	#(matches 11-byte volume label recorded in root dir
FAT32.fat_label			.ascii		"FAT32   "   


#File Allocation Table
#Only uses 28 of 32 bits, top 4 are off limits

fat_offset				.data	8
fat_sector				.data	8
ent_offset				.data 	8

table_value				.data	8


total_secs				.data	8
fat_size				.data	8
root_dir_secs			.data	8
first_data_sec			.data	8
first_fat_sec			.data	8
data_secs				.data	8
total_clusts			.data	8

#Reading directories
root_clust_32			.data	8
first_sec_of_clust		.data	8

#Directory and Data area
#OFFSET		LENGTH	(IN BYTES)
#0			11		FIRST 8 CHARS ARE FILE NAME, LAST 3 EXTENSION
#11			1		ATTRIBUTES
#12			1		RESERVED
#13			1		CREATION TIME IN TENTHS OF A SECOND
#14			2		TIME FILE CREATED - HOUR 5 BITS, MIN 6 BITS, SEC 5 BITS
#16			2		DATE CREATED - YEAR 7 BITS, MONTH 4 BITS, DAY 5 BITS
#18			2		LAST ACCESSED DATE (SAME FORMAT AS DATE CREATED)
#20			2		HIGH 16 BITS OF ENTRYS FIRST CLUSTER NUMBER
#22			2		LAST MODIFICATION TIME (SAME FORMAT AS TIME)
#24			2		LAST MOD DATE (SAME AS DATE)
#26			2		LOW 16 BITS ENTRYS FIRST CLUSTER NUMBER
#28			4		SIZE OF FILE IN BYTES

DIR.name				.data	22
DIR.attr				.data	2
DIR.res					.data	2
DIR.tenth_sec			.data	2
DIR.crt_time			.data	4
DIR.crt_date			.data	4
DIR.accessed			.data	4
DIR.first_clus_hi		.data	4
DIR.last_mod_time		.data	4
DIR.last_mod_date		.data	4
DIR.first_clus_low		.data	4
DIR.size				.data	8

attr.read_only			.data	2	0x01
attr.hidden				.data	2	0x02
attr.system_file		.data	2	0x04	
attr.volume_label		.data	2	0x08
attr.subdirectory		.data	2	0x10
attr.archive			.data	2	0x20

#Temporary values
temp4					.data 	4
temp8					.data	8

